name: Déploiement automatique vers OVH

on:
  push:
    branches:
      - main # Remplace par 'master' si c'est le nom de ta branche principale

jobs:
  deploy:
    name: 🚀 Envoi vers OVH
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Récupération du code
      uses: actions/checkout@v4

    - name: 📂 Synchronisation FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /www/
        exclude: |
          **/.git*
          **/.git*/**
          .github/**
          README.md